Portfolio: mobile version
saruuja/Portfolio_mobile- pull request #3
Opened 2022-04-23 20:54 UTC by saruuja

This is a Portfolio: mobile version built with HTML and CSS linter I added the project two Section Work Section and About me section

2022-04-23 22:36 UTC, dasileker requested changes
### **Hi @saruuja,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## **Highlights**
- Linters are passing ✅. 
- The PR is very nice ✅. 
- The Readme file is good ✅. 


## Required Changes ♻️
_Check the comments under the review._

Hello and nice job on the mobile version, but the `languages`  icons should have a Grey background and the also the `languages` should have the same font as the orner header tag. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 22:36 UTC, dasileker commented on style.css
> +/* Works sectio */
- [ ] Hello and nice job on making the portfolio mobile milestone however, as the requirements says that the main container of the project should be also having a grid layout.

``
![IMG_20220423_222920](https://user-images.githubusercontent.com/61562626/164948114-c006847a-6790-4055-a21b-f59a97c3f682.jpg)

```

2022-04-24 06:06 UTC, saruuja commented
I did all my best and my little experience but  i cant use Grid in work section now because all my project get confused

2022-04-24 11:12 UTC, dasileker commented
> I did all my best and my little experience but  i cant use Grid in work section now because all my project get confused

Hello again, you did a great work but the requirements are requirements tye grid is very simple to use [see here to understand the grid layout](https://www.w3schools.com/css/css_grid.asp)

2022-04-25 12:19 UTC, AnselemOdims requested changes
### Hi @saruuja, 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-25 12:19 UTC, AnselemOdims commented on index.html
> +        <p class="Project_Title">Tonic</p>
- [ ] Please kindly use a `hx` tag for the project titles for semantic purposes.

2022-04-25 12:19 UTC, AnselemOdims commented on index.html
> +       <section class="Works_sectio">
- [ ] Please kindly ensure that each card does not have its own `section` tag, rather the card can be enclosed in a `div` while one `section` tag is used to enclose all cards and displayed as`grid`

2022-04-25 12:19 UTC, AnselemOdims commented on style.css
> +  display: flex;
- [ ] Please kindly ensure to use `display:grid` if this will be the enclosing `section` tag

2022-04-25 12:19 UTC, AnselemOdims commented on index.html
> +           <p class="myself">About Myself</p>
- [ ] Please ensure that the section header `About Myself` uses a `hx` tag

2022-04-25 12:19 UTC, AnselemOdims commented on index.html
> +         <p id="Lests">LET’S CONNECT</p>
- [ ] Please kindly ensure that this uses a `hx` tag

2022-04-25 12:19 UTC, AnselemOdims commented on index.html
> +                 <h3>Skills</h3>
- [ ] Please kindly ensure to put the technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li`

2022-04-25 12:19 UTC, AnselemOdims commented on index.html
> +    <button type="submit" class="btn">See Project</button>
- [ ] Please kindly add styles for the button states(hover, pressed, inactive).

![image](https://user-images.githubusercontent.com/43995830/165087046-3107dbaf-fe2a-42fc-b08c-0940a9a60cf5.png)

2022-04-25 12:19 UTC, AnselemOdims commented on style.css
> +
- [ ] The site is not responsive at the moment, please kindly remove the fixed width and make it more responsive

![image](https://user-images.githubusercontent.com/43995830/165087449-9f08b5a0-c3ce-49db-a724-885a17854b6a.png)

2022-04-25 22:33 UTC, Munsa1 requested changes
Hi @saruuja , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Gitflow :heavy_check_mark:
- Linters Passing :heavy_check_mark:
- Professional readme :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._
- [ ] As requested by the previous reviewer, your site is not responsive, this usually occurs when you give classes fixed `height` and fixed `width`. Kindly check all elements where you have added these properties and remove them.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Refer to the inline comment marked optional

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-25 22:33 UTC, Munsa1 commented on index.html
> +                        <p class="Lests">LET’S CONNECT</p>
Again here, as requested by the previous reviewer, kindly change the "LET'S CONNECT" part of the code by wrapping the text in an `h2` tag instead of the `p` tag for semantic purposes.

2022-04-25 22:33 UTC, Munsa1 commented on index.html
> +                        <ul class="social_Media-two">
- [ ] OPTIONAL
You have organized your code in a cleaner manner for readability like the option below...

![image](https://user-images.githubusercontent.com/81932478/165184283-c2bf25bb-3a80-4635-876f-c5694bd91aef.png)

2022-04-26 06:54 UTC, saruuja commented
This is a Portfolio: mobile version built with HTML and CSS linter I change the p tag to h2 tag in line with proper HTML and CSS semantics.

2022-04-26 07:14 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @saruuja👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

## Optional suggestions
- [ ] I would recommend increasing the font weight for all the headings in your project, This will increase the readability for the users and will also make sure that the project matches with the Template.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 07:24 UTC, merged